name: "CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: "Setup Node.js"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: "Install dependencies"
        run: npm install

      - name: "Test"
        run: npm run test
